// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: wifi_config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Espressif {

  /// <summary>Holder for reflection information generated from wifi_config.proto</summary>
  public static partial class WifiConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for wifi_config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WifiConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChF3aWZpX2NvbmZpZy5wcm90bxIJZXNwcmVzc2lmGg9jb25zdGFudHMucHJv",
            "dG8aFHdpZmlfY29uc3RhbnRzLnByb3RvIg4KDENtZEdldFN0YXR1cyLaAQoN",
            "UmVzcEdldFN0YXR1cxIhCgZzdGF0dXMYASABKA4yES5lc3ByZXNzaWYuU3Rh",
            "dHVzEi4KCXN0YV9zdGF0ZRgCIAEoDjIbLmVzcHJlc3NpZi5XaWZpU3RhdGlv",
            "blN0YXRlEjkKC2ZhaWxfcmVhc29uGAogASgOMiIuZXNwcmVzc2lmLldpZmlD",
            "b25uZWN0RmFpbGVkUmVhc29uSAASMgoJY29ubmVjdGVkGAsgASgLMh0uZXNw",
            "cmVzc2lmLldpZmlDb25uZWN0ZWRTdGF0ZUgAQgcKBXN0YXRlIlAKDENtZFNl",
            "dENvbmZpZxIMCgRzc2lkGAEgASgMEhIKCnBhc3NwaHJhc2UYAiABKAwSDQoF",
            "YnNzaWQYAyABKAwSDwoHY2hhbm5lbBgEIAEoBSIyCg1SZXNwU2V0Q29uZmln",
            "EiEKBnN0YXR1cxgBIAEoDjIRLmVzcHJlc3NpZi5TdGF0dXMiEAoOQ21kQXBw",
            "bHlDb25maWciNAoPUmVzcEFwcGx5Q29uZmlnEiEKBnN0YXR1cxgBIAEoDjIR",
            "LmVzcHJlc3NpZi5TdGF0dXMiiQMKEVdpRmlDb25maWdQYXlsb2FkEikKA21z",
            "ZxgBIAEoDjIcLmVzcHJlc3NpZi5XaUZpQ29uZmlnTXNnVHlwZRIxCg5jbWRf",
            "Z2V0X3N0YXR1cxgKIAEoCzIXLmVzcHJlc3NpZi5DbWRHZXRTdGF0dXNIABIz",
            "Cg9yZXNwX2dldF9zdGF0dXMYCyABKAsyGC5lc3ByZXNzaWYuUmVzcEdldFN0",
            "YXR1c0gAEjEKDmNtZF9zZXRfY29uZmlnGAwgASgLMhcuZXNwcmVzc2lmLkNt",
            "ZFNldENvbmZpZ0gAEjMKD3Jlc3Bfc2V0X2NvbmZpZxgNIAEoCzIYLmVzcHJl",
            "c3NpZi5SZXNwU2V0Q29uZmlnSAASNQoQY21kX2FwcGx5X2NvbmZpZxgOIAEo",
            "CzIZLmVzcHJlc3NpZi5DbWRBcHBseUNvbmZpZ0gAEjcKEXJlc3BfYXBwbHlf",
            "Y29uZmlnGA8gASgLMhouZXNwcmVzc2lmLlJlc3BBcHBseUNvbmZpZ0gAQgkK",
            "B3BheWxvYWQqngEKEVdpRmlDb25maWdNc2dUeXBlEhQKEFR5cGVDbWRHZXRT",
            "dGF0dXMQABIVChFUeXBlUmVzcEdldFN0YXR1cxABEhQKEFR5cGVDbWRTZXRD",
            "b25maWcQAhIVChFUeXBlUmVzcFNldENvbmZpZxADEhYKElR5cGVDbWRBcHBs",
            "eUNvbmZpZxAEEhcKE1R5cGVSZXNwQXBwbHlDb25maWcQBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Espressif.ConstantsReflection.Descriptor, global::Espressif.WifiConstantsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Espressif.WiFiConfigMsgType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Espressif.CmdGetStatus), global::Espressif.CmdGetStatus.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Espressif.RespGetStatus), global::Espressif.RespGetStatus.Parser, new[]{ "Status", "StaState", "FailReason", "Connected" }, new[]{ "State" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Espressif.CmdSetConfig), global::Espressif.CmdSetConfig.Parser, new[]{ "Ssid", "Passphrase", "Bssid", "Channel" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Espressif.RespSetConfig), global::Espressif.RespSetConfig.Parser, new[]{ "Status" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Espressif.CmdApplyConfig), global::Espressif.CmdApplyConfig.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Espressif.RespApplyConfig), global::Espressif.RespApplyConfig.Parser, new[]{ "Status" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Espressif.WiFiConfigPayload), global::Espressif.WiFiConfigPayload.Parser, new[]{ "Msg", "CmdGetStatus", "RespGetStatus", "CmdSetConfig", "RespSetConfig", "CmdApplyConfig", "RespApplyConfig" }, new[]{ "Payload" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum WiFiConfigMsgType {
    [pbr::OriginalName("TypeCmdGetStatus")] TypeCmdGetStatus = 0,
    [pbr::OriginalName("TypeRespGetStatus")] TypeRespGetStatus = 1,
    [pbr::OriginalName("TypeCmdSetConfig")] TypeCmdSetConfig = 2,
    [pbr::OriginalName("TypeRespSetConfig")] TypeRespSetConfig = 3,
    [pbr::OriginalName("TypeCmdApplyConfig")] TypeCmdApplyConfig = 4,
    [pbr::OriginalName("TypeRespApplyConfig")] TypeRespApplyConfig = 5,
  }

  #endregion

  #region Messages
  public sealed partial class CmdGetStatus : pb::IMessage<CmdGetStatus>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CmdGetStatus> _parser = new pb::MessageParser<CmdGetStatus>(() => new CmdGetStatus());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CmdGetStatus> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Espressif.WifiConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CmdGetStatus() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CmdGetStatus(CmdGetStatus other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CmdGetStatus Clone() {
      return new CmdGetStatus(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CmdGetStatus);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CmdGetStatus other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CmdGetStatus other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class RespGetStatus : pb::IMessage<RespGetStatus>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RespGetStatus> _parser = new pb::MessageParser<RespGetStatus>(() => new RespGetStatus());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RespGetStatus> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Espressif.WifiConfigReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespGetStatus() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespGetStatus(RespGetStatus other) : this() {
      status_ = other.status_;
      staState_ = other.staState_;
      switch (other.StateCase) {
        case StateOneofCase.FailReason:
          FailReason = other.FailReason;
          break;
        case StateOneofCase.Connected:
          Connected = other.Connected.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespGetStatus Clone() {
      return new RespGetStatus(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private global::Espressif.Status status_ = global::Espressif.Status.Success;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Espressif.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "sta_state" field.</summary>
    public const int StaStateFieldNumber = 2;
    private global::Espressif.WifiStationState staState_ = global::Espressif.WifiStationState.Connected;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Espressif.WifiStationState StaState {
      get { return staState_; }
      set {
        staState_ = value;
      }
    }

    /// <summary>Field number for the "fail_reason" field.</summary>
    public const int FailReasonFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Espressif.WifiConnectFailedReason FailReason {
      get { return stateCase_ == StateOneofCase.FailReason ? (global::Espressif.WifiConnectFailedReason) state_ : global::Espressif.WifiConnectFailedReason.AuthError; }
      set {
        state_ = value;
        stateCase_ = StateOneofCase.FailReason;
      }
    }

    /// <summary>Field number for the "connected" field.</summary>
    public const int ConnectedFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Espressif.WifiConnectedState Connected {
      get { return stateCase_ == StateOneofCase.Connected ? (global::Espressif.WifiConnectedState) state_ : null; }
      set {
        state_ = value;
        stateCase_ = value == null ? StateOneofCase.None : StateOneofCase.Connected;
      }
    }

    private object state_;
    /// <summary>Enum of possible cases for the "state" oneof.</summary>
    public enum StateOneofCase {
      None = 0,
      FailReason = 10,
      Connected = 11,
    }
    private StateOneofCase stateCase_ = StateOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StateOneofCase StateCase {
      get { return stateCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearState() {
      stateCase_ = StateOneofCase.None;
      state_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RespGetStatus);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RespGetStatus other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      if (StaState != other.StaState) return false;
      if (FailReason != other.FailReason) return false;
      if (!object.Equals(Connected, other.Connected)) return false;
      if (StateCase != other.StateCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != global::Espressif.Status.Success) hash ^= Status.GetHashCode();
      if (StaState != global::Espressif.WifiStationState.Connected) hash ^= StaState.GetHashCode();
      if (stateCase_ == StateOneofCase.FailReason) hash ^= FailReason.GetHashCode();
      if (stateCase_ == StateOneofCase.Connected) hash ^= Connected.GetHashCode();
      hash ^= (int) stateCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Status != global::Espressif.Status.Success) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (StaState != global::Espressif.WifiStationState.Connected) {
        output.WriteRawTag(16);
        output.WriteEnum((int) StaState);
      }
      if (stateCase_ == StateOneofCase.FailReason) {
        output.WriteRawTag(80);
        output.WriteEnum((int) FailReason);
      }
      if (stateCase_ == StateOneofCase.Connected) {
        output.WriteRawTag(90);
        output.WriteMessage(Connected);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Status != global::Espressif.Status.Success) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (StaState != global::Espressif.WifiStationState.Connected) {
        output.WriteRawTag(16);
        output.WriteEnum((int) StaState);
      }
      if (stateCase_ == StateOneofCase.FailReason) {
        output.WriteRawTag(80);
        output.WriteEnum((int) FailReason);
      }
      if (stateCase_ == StateOneofCase.Connected) {
        output.WriteRawTag(90);
        output.WriteMessage(Connected);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Status != global::Espressif.Status.Success) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (StaState != global::Espressif.WifiStationState.Connected) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) StaState);
      }
      if (stateCase_ == StateOneofCase.FailReason) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) FailReason);
      }
      if (stateCase_ == StateOneofCase.Connected) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Connected);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RespGetStatus other) {
      if (other == null) {
        return;
      }
      if (other.Status != global::Espressif.Status.Success) {
        Status = other.Status;
      }
      if (other.StaState != global::Espressif.WifiStationState.Connected) {
        StaState = other.StaState;
      }
      switch (other.StateCase) {
        case StateOneofCase.FailReason:
          FailReason = other.FailReason;
          break;
        case StateOneofCase.Connected:
          if (Connected == null) {
            Connected = new global::Espressif.WifiConnectedState();
          }
          Connected.MergeFrom(other.Connected);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Status = (global::Espressif.Status) input.ReadEnum();
            break;
          }
          case 16: {
            StaState = (global::Espressif.WifiStationState) input.ReadEnum();
            break;
          }
          case 80: {
            state_ = input.ReadEnum();
            stateCase_ = StateOneofCase.FailReason;
            break;
          }
          case 90: {
            global::Espressif.WifiConnectedState subBuilder = new global::Espressif.WifiConnectedState();
            if (stateCase_ == StateOneofCase.Connected) {
              subBuilder.MergeFrom(Connected);
            }
            input.ReadMessage(subBuilder);
            Connected = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Status = (global::Espressif.Status) input.ReadEnum();
            break;
          }
          case 16: {
            StaState = (global::Espressif.WifiStationState) input.ReadEnum();
            break;
          }
          case 80: {
            state_ = input.ReadEnum();
            stateCase_ = StateOneofCase.FailReason;
            break;
          }
          case 90: {
            global::Espressif.WifiConnectedState subBuilder = new global::Espressif.WifiConnectedState();
            if (stateCase_ == StateOneofCase.Connected) {
              subBuilder.MergeFrom(Connected);
            }
            input.ReadMessage(subBuilder);
            Connected = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CmdSetConfig : pb::IMessage<CmdSetConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CmdSetConfig> _parser = new pb::MessageParser<CmdSetConfig>(() => new CmdSetConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CmdSetConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Espressif.WifiConfigReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CmdSetConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CmdSetConfig(CmdSetConfig other) : this() {
      ssid_ = other.ssid_;
      passphrase_ = other.passphrase_;
      bssid_ = other.bssid_;
      channel_ = other.channel_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CmdSetConfig Clone() {
      return new CmdSetConfig(this);
    }

    /// <summary>Field number for the "ssid" field.</summary>
    public const int SsidFieldNumber = 1;
    private pb::ByteString ssid_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Ssid {
      get { return ssid_; }
      set {
        ssid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "passphrase" field.</summary>
    public const int PassphraseFieldNumber = 2;
    private pb::ByteString passphrase_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Passphrase {
      get { return passphrase_; }
      set {
        passphrase_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bssid" field.</summary>
    public const int BssidFieldNumber = 3;
    private pb::ByteString bssid_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Bssid {
      get { return bssid_; }
      set {
        bssid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "channel" field.</summary>
    public const int ChannelFieldNumber = 4;
    private int channel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Channel {
      get { return channel_; }
      set {
        channel_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CmdSetConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CmdSetConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Ssid != other.Ssid) return false;
      if (Passphrase != other.Passphrase) return false;
      if (Bssid != other.Bssid) return false;
      if (Channel != other.Channel) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Ssid.Length != 0) hash ^= Ssid.GetHashCode();
      if (Passphrase.Length != 0) hash ^= Passphrase.GetHashCode();
      if (Bssid.Length != 0) hash ^= Bssid.GetHashCode();
      if (Channel != 0) hash ^= Channel.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Ssid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Ssid);
      }
      if (Passphrase.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Passphrase);
      }
      if (Bssid.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Bssid);
      }
      if (Channel != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Channel);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Ssid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Ssid);
      }
      if (Passphrase.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Passphrase);
      }
      if (Bssid.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Bssid);
      }
      if (Channel != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Channel);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Ssid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Ssid);
      }
      if (Passphrase.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Passphrase);
      }
      if (Bssid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Bssid);
      }
      if (Channel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Channel);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CmdSetConfig other) {
      if (other == null) {
        return;
      }
      if (other.Ssid.Length != 0) {
        Ssid = other.Ssid;
      }
      if (other.Passphrase.Length != 0) {
        Passphrase = other.Passphrase;
      }
      if (other.Bssid.Length != 0) {
        Bssid = other.Bssid;
      }
      if (other.Channel != 0) {
        Channel = other.Channel;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Ssid = input.ReadBytes();
            break;
          }
          case 18: {
            Passphrase = input.ReadBytes();
            break;
          }
          case 26: {
            Bssid = input.ReadBytes();
            break;
          }
          case 32: {
            Channel = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Ssid = input.ReadBytes();
            break;
          }
          case 18: {
            Passphrase = input.ReadBytes();
            break;
          }
          case 26: {
            Bssid = input.ReadBytes();
            break;
          }
          case 32: {
            Channel = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RespSetConfig : pb::IMessage<RespSetConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RespSetConfig> _parser = new pb::MessageParser<RespSetConfig>(() => new RespSetConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RespSetConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Espressif.WifiConfigReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespSetConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespSetConfig(RespSetConfig other) : this() {
      status_ = other.status_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespSetConfig Clone() {
      return new RespSetConfig(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private global::Espressif.Status status_ = global::Espressif.Status.Success;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Espressif.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RespSetConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RespSetConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != global::Espressif.Status.Success) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Status != global::Espressif.Status.Success) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Status != global::Espressif.Status.Success) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Status != global::Espressif.Status.Success) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RespSetConfig other) {
      if (other == null) {
        return;
      }
      if (other.Status != global::Espressif.Status.Success) {
        Status = other.Status;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Status = (global::Espressif.Status) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Status = (global::Espressif.Status) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CmdApplyConfig : pb::IMessage<CmdApplyConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CmdApplyConfig> _parser = new pb::MessageParser<CmdApplyConfig>(() => new CmdApplyConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CmdApplyConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Espressif.WifiConfigReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CmdApplyConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CmdApplyConfig(CmdApplyConfig other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CmdApplyConfig Clone() {
      return new CmdApplyConfig(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CmdApplyConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CmdApplyConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CmdApplyConfig other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class RespApplyConfig : pb::IMessage<RespApplyConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RespApplyConfig> _parser = new pb::MessageParser<RespApplyConfig>(() => new RespApplyConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RespApplyConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Espressif.WifiConfigReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespApplyConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespApplyConfig(RespApplyConfig other) : this() {
      status_ = other.status_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespApplyConfig Clone() {
      return new RespApplyConfig(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private global::Espressif.Status status_ = global::Espressif.Status.Success;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Espressif.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RespApplyConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RespApplyConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != global::Espressif.Status.Success) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Status != global::Espressif.Status.Success) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Status != global::Espressif.Status.Success) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Status != global::Espressif.Status.Success) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RespApplyConfig other) {
      if (other == null) {
        return;
      }
      if (other.Status != global::Espressif.Status.Success) {
        Status = other.Status;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Status = (global::Espressif.Status) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Status = (global::Espressif.Status) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class WiFiConfigPayload : pb::IMessage<WiFiConfigPayload>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WiFiConfigPayload> _parser = new pb::MessageParser<WiFiConfigPayload>(() => new WiFiConfigPayload());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WiFiConfigPayload> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Espressif.WifiConfigReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WiFiConfigPayload() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WiFiConfigPayload(WiFiConfigPayload other) : this() {
      msg_ = other.msg_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.CmdGetStatus:
          CmdGetStatus = other.CmdGetStatus.Clone();
          break;
        case PayloadOneofCase.RespGetStatus:
          RespGetStatus = other.RespGetStatus.Clone();
          break;
        case PayloadOneofCase.CmdSetConfig:
          CmdSetConfig = other.CmdSetConfig.Clone();
          break;
        case PayloadOneofCase.RespSetConfig:
          RespSetConfig = other.RespSetConfig.Clone();
          break;
        case PayloadOneofCase.CmdApplyConfig:
          CmdApplyConfig = other.CmdApplyConfig.Clone();
          break;
        case PayloadOneofCase.RespApplyConfig:
          RespApplyConfig = other.RespApplyConfig.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WiFiConfigPayload Clone() {
      return new WiFiConfigPayload(this);
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 1;
    private global::Espressif.WiFiConfigMsgType msg_ = global::Espressif.WiFiConfigMsgType.TypeCmdGetStatus;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Espressif.WiFiConfigMsgType Msg {
      get { return msg_; }
      set {
        msg_ = value;
      }
    }

    /// <summary>Field number for the "cmd_get_status" field.</summary>
    public const int CmdGetStatusFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Espressif.CmdGetStatus CmdGetStatus {
      get { return payloadCase_ == PayloadOneofCase.CmdGetStatus ? (global::Espressif.CmdGetStatus) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.CmdGetStatus;
      }
    }

    /// <summary>Field number for the "resp_get_status" field.</summary>
    public const int RespGetStatusFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Espressif.RespGetStatus RespGetStatus {
      get { return payloadCase_ == PayloadOneofCase.RespGetStatus ? (global::Espressif.RespGetStatus) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.RespGetStatus;
      }
    }

    /// <summary>Field number for the "cmd_set_config" field.</summary>
    public const int CmdSetConfigFieldNumber = 12;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Espressif.CmdSetConfig CmdSetConfig {
      get { return payloadCase_ == PayloadOneofCase.CmdSetConfig ? (global::Espressif.CmdSetConfig) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.CmdSetConfig;
      }
    }

    /// <summary>Field number for the "resp_set_config" field.</summary>
    public const int RespSetConfigFieldNumber = 13;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Espressif.RespSetConfig RespSetConfig {
      get { return payloadCase_ == PayloadOneofCase.RespSetConfig ? (global::Espressif.RespSetConfig) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.RespSetConfig;
      }
    }

    /// <summary>Field number for the "cmd_apply_config" field.</summary>
    public const int CmdApplyConfigFieldNumber = 14;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Espressif.CmdApplyConfig CmdApplyConfig {
      get { return payloadCase_ == PayloadOneofCase.CmdApplyConfig ? (global::Espressif.CmdApplyConfig) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.CmdApplyConfig;
      }
    }

    /// <summary>Field number for the "resp_apply_config" field.</summary>
    public const int RespApplyConfigFieldNumber = 15;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Espressif.RespApplyConfig RespApplyConfig {
      get { return payloadCase_ == PayloadOneofCase.RespApplyConfig ? (global::Espressif.RespApplyConfig) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.RespApplyConfig;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      CmdGetStatus = 10,
      RespGetStatus = 11,
      CmdSetConfig = 12,
      RespSetConfig = 13,
      CmdApplyConfig = 14,
      RespApplyConfig = 15,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WiFiConfigPayload);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WiFiConfigPayload other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Msg != other.Msg) return false;
      if (!object.Equals(CmdGetStatus, other.CmdGetStatus)) return false;
      if (!object.Equals(RespGetStatus, other.RespGetStatus)) return false;
      if (!object.Equals(CmdSetConfig, other.CmdSetConfig)) return false;
      if (!object.Equals(RespSetConfig, other.RespSetConfig)) return false;
      if (!object.Equals(CmdApplyConfig, other.CmdApplyConfig)) return false;
      if (!object.Equals(RespApplyConfig, other.RespApplyConfig)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Msg != global::Espressif.WiFiConfigMsgType.TypeCmdGetStatus) hash ^= Msg.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.CmdGetStatus) hash ^= CmdGetStatus.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.RespGetStatus) hash ^= RespGetStatus.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.CmdSetConfig) hash ^= CmdSetConfig.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.RespSetConfig) hash ^= RespSetConfig.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.CmdApplyConfig) hash ^= CmdApplyConfig.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.RespApplyConfig) hash ^= RespApplyConfig.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Msg != global::Espressif.WiFiConfigMsgType.TypeCmdGetStatus) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Msg);
      }
      if (payloadCase_ == PayloadOneofCase.CmdGetStatus) {
        output.WriteRawTag(82);
        output.WriteMessage(CmdGetStatus);
      }
      if (payloadCase_ == PayloadOneofCase.RespGetStatus) {
        output.WriteRawTag(90);
        output.WriteMessage(RespGetStatus);
      }
      if (payloadCase_ == PayloadOneofCase.CmdSetConfig) {
        output.WriteRawTag(98);
        output.WriteMessage(CmdSetConfig);
      }
      if (payloadCase_ == PayloadOneofCase.RespSetConfig) {
        output.WriteRawTag(106);
        output.WriteMessage(RespSetConfig);
      }
      if (payloadCase_ == PayloadOneofCase.CmdApplyConfig) {
        output.WriteRawTag(114);
        output.WriteMessage(CmdApplyConfig);
      }
      if (payloadCase_ == PayloadOneofCase.RespApplyConfig) {
        output.WriteRawTag(122);
        output.WriteMessage(RespApplyConfig);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Msg != global::Espressif.WiFiConfigMsgType.TypeCmdGetStatus) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Msg);
      }
      if (payloadCase_ == PayloadOneofCase.CmdGetStatus) {
        output.WriteRawTag(82);
        output.WriteMessage(CmdGetStatus);
      }
      if (payloadCase_ == PayloadOneofCase.RespGetStatus) {
        output.WriteRawTag(90);
        output.WriteMessage(RespGetStatus);
      }
      if (payloadCase_ == PayloadOneofCase.CmdSetConfig) {
        output.WriteRawTag(98);
        output.WriteMessage(CmdSetConfig);
      }
      if (payloadCase_ == PayloadOneofCase.RespSetConfig) {
        output.WriteRawTag(106);
        output.WriteMessage(RespSetConfig);
      }
      if (payloadCase_ == PayloadOneofCase.CmdApplyConfig) {
        output.WriteRawTag(114);
        output.WriteMessage(CmdApplyConfig);
      }
      if (payloadCase_ == PayloadOneofCase.RespApplyConfig) {
        output.WriteRawTag(122);
        output.WriteMessage(RespApplyConfig);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Msg != global::Espressif.WiFiConfigMsgType.TypeCmdGetStatus) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Msg);
      }
      if (payloadCase_ == PayloadOneofCase.CmdGetStatus) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CmdGetStatus);
      }
      if (payloadCase_ == PayloadOneofCase.RespGetStatus) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RespGetStatus);
      }
      if (payloadCase_ == PayloadOneofCase.CmdSetConfig) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CmdSetConfig);
      }
      if (payloadCase_ == PayloadOneofCase.RespSetConfig) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RespSetConfig);
      }
      if (payloadCase_ == PayloadOneofCase.CmdApplyConfig) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CmdApplyConfig);
      }
      if (payloadCase_ == PayloadOneofCase.RespApplyConfig) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RespApplyConfig);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WiFiConfigPayload other) {
      if (other == null) {
        return;
      }
      if (other.Msg != global::Espressif.WiFiConfigMsgType.TypeCmdGetStatus) {
        Msg = other.Msg;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.CmdGetStatus:
          if (CmdGetStatus == null) {
            CmdGetStatus = new global::Espressif.CmdGetStatus();
          }
          CmdGetStatus.MergeFrom(other.CmdGetStatus);
          break;
        case PayloadOneofCase.RespGetStatus:
          if (RespGetStatus == null) {
            RespGetStatus = new global::Espressif.RespGetStatus();
          }
          RespGetStatus.MergeFrom(other.RespGetStatus);
          break;
        case PayloadOneofCase.CmdSetConfig:
          if (CmdSetConfig == null) {
            CmdSetConfig = new global::Espressif.CmdSetConfig();
          }
          CmdSetConfig.MergeFrom(other.CmdSetConfig);
          break;
        case PayloadOneofCase.RespSetConfig:
          if (RespSetConfig == null) {
            RespSetConfig = new global::Espressif.RespSetConfig();
          }
          RespSetConfig.MergeFrom(other.RespSetConfig);
          break;
        case PayloadOneofCase.CmdApplyConfig:
          if (CmdApplyConfig == null) {
            CmdApplyConfig = new global::Espressif.CmdApplyConfig();
          }
          CmdApplyConfig.MergeFrom(other.CmdApplyConfig);
          break;
        case PayloadOneofCase.RespApplyConfig:
          if (RespApplyConfig == null) {
            RespApplyConfig = new global::Espressif.RespApplyConfig();
          }
          RespApplyConfig.MergeFrom(other.RespApplyConfig);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Msg = (global::Espressif.WiFiConfigMsgType) input.ReadEnum();
            break;
          }
          case 82: {
            global::Espressif.CmdGetStatus subBuilder = new global::Espressif.CmdGetStatus();
            if (payloadCase_ == PayloadOneofCase.CmdGetStatus) {
              subBuilder.MergeFrom(CmdGetStatus);
            }
            input.ReadMessage(subBuilder);
            CmdGetStatus = subBuilder;
            break;
          }
          case 90: {
            global::Espressif.RespGetStatus subBuilder = new global::Espressif.RespGetStatus();
            if (payloadCase_ == PayloadOneofCase.RespGetStatus) {
              subBuilder.MergeFrom(RespGetStatus);
            }
            input.ReadMessage(subBuilder);
            RespGetStatus = subBuilder;
            break;
          }
          case 98: {
            global::Espressif.CmdSetConfig subBuilder = new global::Espressif.CmdSetConfig();
            if (payloadCase_ == PayloadOneofCase.CmdSetConfig) {
              subBuilder.MergeFrom(CmdSetConfig);
            }
            input.ReadMessage(subBuilder);
            CmdSetConfig = subBuilder;
            break;
          }
          case 106: {
            global::Espressif.RespSetConfig subBuilder = new global::Espressif.RespSetConfig();
            if (payloadCase_ == PayloadOneofCase.RespSetConfig) {
              subBuilder.MergeFrom(RespSetConfig);
            }
            input.ReadMessage(subBuilder);
            RespSetConfig = subBuilder;
            break;
          }
          case 114: {
            global::Espressif.CmdApplyConfig subBuilder = new global::Espressif.CmdApplyConfig();
            if (payloadCase_ == PayloadOneofCase.CmdApplyConfig) {
              subBuilder.MergeFrom(CmdApplyConfig);
            }
            input.ReadMessage(subBuilder);
            CmdApplyConfig = subBuilder;
            break;
          }
          case 122: {
            global::Espressif.RespApplyConfig subBuilder = new global::Espressif.RespApplyConfig();
            if (payloadCase_ == PayloadOneofCase.RespApplyConfig) {
              subBuilder.MergeFrom(RespApplyConfig);
            }
            input.ReadMessage(subBuilder);
            RespApplyConfig = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Msg = (global::Espressif.WiFiConfigMsgType) input.ReadEnum();
            break;
          }
          case 82: {
            global::Espressif.CmdGetStatus subBuilder = new global::Espressif.CmdGetStatus();
            if (payloadCase_ == PayloadOneofCase.CmdGetStatus) {
              subBuilder.MergeFrom(CmdGetStatus);
            }
            input.ReadMessage(subBuilder);
            CmdGetStatus = subBuilder;
            break;
          }
          case 90: {
            global::Espressif.RespGetStatus subBuilder = new global::Espressif.RespGetStatus();
            if (payloadCase_ == PayloadOneofCase.RespGetStatus) {
              subBuilder.MergeFrom(RespGetStatus);
            }
            input.ReadMessage(subBuilder);
            RespGetStatus = subBuilder;
            break;
          }
          case 98: {
            global::Espressif.CmdSetConfig subBuilder = new global::Espressif.CmdSetConfig();
            if (payloadCase_ == PayloadOneofCase.CmdSetConfig) {
              subBuilder.MergeFrom(CmdSetConfig);
            }
            input.ReadMessage(subBuilder);
            CmdSetConfig = subBuilder;
            break;
          }
          case 106: {
            global::Espressif.RespSetConfig subBuilder = new global::Espressif.RespSetConfig();
            if (payloadCase_ == PayloadOneofCase.RespSetConfig) {
              subBuilder.MergeFrom(RespSetConfig);
            }
            input.ReadMessage(subBuilder);
            RespSetConfig = subBuilder;
            break;
          }
          case 114: {
            global::Espressif.CmdApplyConfig subBuilder = new global::Espressif.CmdApplyConfig();
            if (payloadCase_ == PayloadOneofCase.CmdApplyConfig) {
              subBuilder.MergeFrom(CmdApplyConfig);
            }
            input.ReadMessage(subBuilder);
            CmdApplyConfig = subBuilder;
            break;
          }
          case 122: {
            global::Espressif.RespApplyConfig subBuilder = new global::Espressif.RespApplyConfig();
            if (payloadCase_ == PayloadOneofCase.RespApplyConfig) {
              subBuilder.MergeFrom(RespApplyConfig);
            }
            input.ReadMessage(subBuilder);
            RespApplyConfig = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
