// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: wifi_scan.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using System;
using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Espressif {

  /// <summary>Holder for reflection information generated from wifi_scan.proto</summary>
  public static partial class WifiScanReflection {

    #region Descriptor
    /// <summary>File descriptor for wifi_scan.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WifiScanReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg93aWZpX3NjYW4ucHJvdG8SCWVzcHJlc3NpZhoPY29uc3RhbnRzLnByb3Rv",
            "GhR3aWZpX2NvbnN0YW50cy5wcm90byJcCgxDbWRTY2FuU3RhcnQSEAoIYmxv",
            "Y2tpbmcYASABKAgSDwoHcGFzc2l2ZRgCIAEoCBIWCg5ncm91cF9jaGFubmVs",
            "cxgDIAEoDRIRCglwZXJpb2RfbXMYBCABKA0iDwoNUmVzcFNjYW5TdGFydCIP",
            "Cg1DbWRTY2FuU3RhdHVzIj0KDlJlc3BTY2FuU3RhdHVzEhUKDXNjYW5fZmlu",
            "aXNoZWQYASABKAgSFAoMcmVzdWx0X2NvdW50GAIgASgNIjMKDUNtZFNjYW5S",
            "ZXN1bHQSEwoLc3RhcnRfaW5kZXgYASABKA0SDQoFY291bnQYAiABKA0icwoO",
            "V2lGaVNjYW5SZXN1bHQSDAoEc3NpZBgBIAEoDBIPCgdjaGFubmVsGAIgASgN",
            "EgwKBHJzc2kYAyABKAUSDQoFYnNzaWQYBCABKAwSJQoEYXV0aBgFIAEoDjIX",
            "LmVzcHJlc3NpZi5XaWZpQXV0aE1vZGUiPAoOUmVzcFNjYW5SZXN1bHQSKgoH",
            "ZW50cmllcxgBIAMoCzIZLmVzcHJlc3NpZi5XaUZpU2NhblJlc3VsdCKoAwoP",
            "V2lGaVNjYW5QYXlsb2FkEicKA21zZxgBIAEoDjIaLmVzcHJlc3NpZi5XaUZp",
            "U2Nhbk1zZ1R5cGUSIQoGc3RhdHVzGAIgASgOMhEuZXNwcmVzc2lmLlN0YXR1",
            "cxIxCg5jbWRfc2Nhbl9zdGFydBgKIAEoCzIXLmVzcHJlc3NpZi5DbWRTY2Fu",
            "U3RhcnRIABIzCg9yZXNwX3NjYW5fc3RhcnQYCyABKAsyGC5lc3ByZXNzaWYu",
            "UmVzcFNjYW5TdGFydEgAEjMKD2NtZF9zY2FuX3N0YXR1cxgMIAEoCzIYLmVz",
            "cHJlc3NpZi5DbWRTY2FuU3RhdHVzSAASNQoQcmVzcF9zY2FuX3N0YXR1cxgN",
            "IAEoCzIZLmVzcHJlc3NpZi5SZXNwU2NhblN0YXR1c0gAEjMKD2NtZF9zY2Fu",
            "X3Jlc3VsdBgOIAEoCzIYLmVzcHJlc3NpZi5DbWRTY2FuUmVzdWx0SAASNQoQ",
            "cmVzcF9zY2FuX3Jlc3VsdBgPIAEoCzIZLmVzcHJlc3NpZi5SZXNwU2NhblJl",
            "c3VsdEgAQgkKB3BheWxvYWQqnAEKD1dpRmlTY2FuTXNnVHlwZRIUChBUeXBl",
            "Q21kU2NhblN0YXJ0EAASFQoRVHlwZVJlc3BTY2FuU3RhcnQQARIVChFUeXBl",
            "Q21kU2NhblN0YXR1cxACEhYKElR5cGVSZXNwU2NhblN0YXR1cxADEhUKEVR5",
            "cGVDbWRTY2FuUmVzdWx0EAQSFgoSVHlwZVJlc3BTY2FuUmVzdWx0EAViBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Espressif.ConstantsReflection.Descriptor, global::Espressif.WifiConstantsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Espressif.WiFiScanMsgType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Espressif.CmdScanStart), global::Espressif.CmdScanStart.Parser, new[]{ "Blocking", "Passive", "GroupChannels", "PeriodMs" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Espressif.RespScanStart), global::Espressif.RespScanStart.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Espressif.CmdScanStatus), global::Espressif.CmdScanStatus.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Espressif.RespScanStatus), global::Espressif.RespScanStatus.Parser, new[]{ "ScanFinished", "ResultCount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Espressif.CmdScanResult), global::Espressif.CmdScanResult.Parser, new[]{ "StartIndex", "Count" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Espressif.WiFiScanResult), global::Espressif.WiFiScanResult.Parser, new[]{ "Ssid", "Channel", "Rssi", "Bssid", "Auth" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Espressif.RespScanResult), global::Espressif.RespScanResult.Parser, new[]{ "Entries" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Espressif.WiFiScanPayload), global::Espressif.WiFiScanPayload.Parser, new[]{ "Msg", "Status", "CmdScanStart", "RespScanStart", "CmdScanStatus", "RespScanStatus", "CmdScanResult", "RespScanResult" }, new[]{ "Payload" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum WiFiScanMsgType {
    [pbr::OriginalName("TypeCmdScanStart")] TypeCmdScanStart = 0,
    [pbr::OriginalName("TypeRespScanStart")] TypeRespScanStart = 1,
    [pbr::OriginalName("TypeCmdScanStatus")] TypeCmdScanStatus = 2,
    [pbr::OriginalName("TypeRespScanStatus")] TypeRespScanStatus = 3,
    [pbr::OriginalName("TypeCmdScanResult")] TypeCmdScanResult = 4,
    [pbr::OriginalName("TypeRespScanResult")] TypeRespScanResult = 5,
  }

  #endregion

  #region Messages
  public sealed partial class CmdScanStart : pb::IMessage<CmdScanStart>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CmdScanStart> _parser = new pb::MessageParser<CmdScanStart>(() => new CmdScanStart());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CmdScanStart> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Espressif.WifiScanReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CmdScanStart() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CmdScanStart(CmdScanStart other) : this() {
      blocking_ = other.blocking_;
      passive_ = other.passive_;
      groupChannels_ = other.groupChannels_;
      periodMs_ = other.periodMs_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CmdScanStart Clone() {
      return new CmdScanStart(this);
    }

    /// <summary>Field number for the "blocking" field.</summary>
    public const int BlockingFieldNumber = 1;
    private bool blocking_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Blocking {
      get { return blocking_; }
      set {
        blocking_ = value;
      }
    }

    /// <summary>Field number for the "passive" field.</summary>
    public const int PassiveFieldNumber = 2;
    private bool passive_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Passive {
      get { return passive_; }
      set {
        passive_ = value;
      }
    }

    /// <summary>Field number for the "group_channels" field.</summary>
    public const int GroupChannelsFieldNumber = 3;
    private uint groupChannels_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GroupChannels {
      get { return groupChannels_; }
      set {
        groupChannels_ = value;
      }
    }

    /// <summary>Field number for the "period_ms" field.</summary>
    public const int PeriodMsFieldNumber = 4;
    private uint periodMs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PeriodMs {
      get { return periodMs_; }
      set {
        periodMs_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CmdScanStart);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CmdScanStart other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Blocking != other.Blocking) return false;
      if (Passive != other.Passive) return false;
      if (GroupChannels != other.GroupChannels) return false;
      if (PeriodMs != other.PeriodMs) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Blocking != false) hash ^= Blocking.GetHashCode();
      if (Passive != false) hash ^= Passive.GetHashCode();
      if (GroupChannels != 0) hash ^= GroupChannels.GetHashCode();
      if (PeriodMs != 0) hash ^= PeriodMs.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Blocking != false) {
        output.WriteRawTag(8);
        output.WriteBool(Blocking);
      }
      if (Passive != false) {
        output.WriteRawTag(16);
        output.WriteBool(Passive);
      }
      if (GroupChannels != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(GroupChannels);
      }
      if (PeriodMs != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(PeriodMs);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Blocking != false) {
        output.WriteRawTag(8);
        output.WriteBool(Blocking);
      }
      if (Passive != false) {
        output.WriteRawTag(16);
        output.WriteBool(Passive);
      }
      if (GroupChannels != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(GroupChannels);
      }
      if (PeriodMs != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(PeriodMs);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Blocking != false) {
        size += 1 + 1;
      }
      if (Passive != false) {
        size += 1 + 1;
      }
      if (GroupChannels != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GroupChannels);
      }
      if (PeriodMs != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PeriodMs);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CmdScanStart other) {
      if (other == null) {
        return;
      }
      if (other.Blocking != false) {
        Blocking = other.Blocking;
      }
      if (other.Passive != false) {
        Passive = other.Passive;
      }
      if (other.GroupChannels != 0) {
        GroupChannels = other.GroupChannels;
      }
      if (other.PeriodMs != 0) {
        PeriodMs = other.PeriodMs;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Blocking = input.ReadBool();
            break;
          }
          case 16: {
            Passive = input.ReadBool();
            break;
          }
          case 24: {
            GroupChannels = input.ReadUInt32();
            break;
          }
          case 32: {
            PeriodMs = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Blocking = input.ReadBool();
            break;
          }
          case 16: {
            Passive = input.ReadBool();
            break;
          }
          case 24: {
            GroupChannels = input.ReadUInt32();
            break;
          }
          case 32: {
            PeriodMs = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RespScanStart : pb::IMessage<RespScanStart>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RespScanStart> _parser = new pb::MessageParser<RespScanStart>(() => new RespScanStart());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RespScanStart> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Espressif.WifiScanReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespScanStart() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespScanStart(RespScanStart other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespScanStart Clone() {
      return new RespScanStart(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RespScanStart);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RespScanStart other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RespScanStart other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class CmdScanStatus : pb::IMessage<CmdScanStatus>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CmdScanStatus> _parser = new pb::MessageParser<CmdScanStatus>(() => new CmdScanStatus());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CmdScanStatus> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Espressif.WifiScanReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CmdScanStatus() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CmdScanStatus(CmdScanStatus other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CmdScanStatus Clone() {
      return new CmdScanStatus(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CmdScanStatus);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CmdScanStatus other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CmdScanStatus other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class RespScanStatus : pb::IMessage<RespScanStatus>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RespScanStatus> _parser = new pb::MessageParser<RespScanStatus>(() => new RespScanStatus());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RespScanStatus> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Espressif.WifiScanReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespScanStatus() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespScanStatus(RespScanStatus other) : this() {
      scanFinished_ = other.scanFinished_;
      resultCount_ = other.resultCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespScanStatus Clone() {
      return new RespScanStatus(this);
    }

    /// <summary>Field number for the "scan_finished" field.</summary>
    public const int ScanFinishedFieldNumber = 1;
    private bool scanFinished_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ScanFinished {
      get { return scanFinished_; }
      set {
        scanFinished_ = value;
      }
    }

    /// <summary>Field number for the "result_count" field.</summary>
    public const int ResultCountFieldNumber = 2;
    private uint resultCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ResultCount {
      get { return resultCount_; }
      set {
        resultCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RespScanStatus);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RespScanStatus other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ScanFinished != other.ScanFinished) return false;
      if (ResultCount != other.ResultCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ScanFinished != false) hash ^= ScanFinished.GetHashCode();
      if (ResultCount != 0) hash ^= ResultCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ScanFinished != false) {
        output.WriteRawTag(8);
        output.WriteBool(ScanFinished);
      }
      if (ResultCount != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(ResultCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ScanFinished != false) {
        output.WriteRawTag(8);
        output.WriteBool(ScanFinished);
      }
      if (ResultCount != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(ResultCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ScanFinished != false) {
        size += 1 + 1;
      }
      if (ResultCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ResultCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RespScanStatus other) {
      if (other == null) {
        return;
      }
      if (other.ScanFinished != false) {
        ScanFinished = other.ScanFinished;
      }
      if (other.ResultCount != 0) {
        ResultCount = other.ResultCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ScanFinished = input.ReadBool();
            break;
          }
          case 16: {
            ResultCount = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ScanFinished = input.ReadBool();
            break;
          }
          case 16: {
            ResultCount = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CmdScanResult : pb::IMessage<CmdScanResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CmdScanResult> _parser = new pb::MessageParser<CmdScanResult>(() => new CmdScanResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CmdScanResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Espressif.WifiScanReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CmdScanResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CmdScanResult(CmdScanResult other) : this() {
      startIndex_ = other.startIndex_;
      count_ = other.count_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CmdScanResult Clone() {
      return new CmdScanResult(this);
    }

    /// <summary>Field number for the "start_index" field.</summary>
    public const int StartIndexFieldNumber = 1;
    private uint startIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint StartIndex {
      get { return startIndex_; }
      set {
        startIndex_ = value;
      }
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 2;
    private uint count_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CmdScanResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CmdScanResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StartIndex != other.StartIndex) return false;
      if (Count != other.Count) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (StartIndex != 0) hash ^= StartIndex.GetHashCode();
      if (Count != 0) hash ^= Count.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (StartIndex != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(StartIndex);
      }
      if (Count != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Count);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (StartIndex != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(StartIndex);
      }
      if (Count != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Count);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (StartIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(StartIndex);
      }
      if (Count != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Count);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CmdScanResult other) {
      if (other == null) {
        return;
      }
      if (other.StartIndex != 0) {
        StartIndex = other.StartIndex;
      }
      if (other.Count != 0) {
        Count = other.Count;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StartIndex = input.ReadUInt32();
            break;
          }
          case 16: {
            Count = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            StartIndex = input.ReadUInt32();
            break;
          }
          case 16: {
            Count = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class WiFiScanResult : pb::IMessage<WiFiScanResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WiFiScanResult> _parser = new pb::MessageParser<WiFiScanResult>(() => new WiFiScanResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WiFiScanResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Espressif.WifiScanReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WiFiScanResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WiFiScanResult(WiFiScanResult other) : this() {
      ssid_ = other.ssid_;
      channel_ = other.channel_;
      rssi_ = other.rssi_;
      bssid_ = other.bssid_;
      auth_ = other.auth_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WiFiScanResult Clone() {
      return new WiFiScanResult(this);
    }

    /// <summary>Field number for the "ssid" field.</summary>
    public const int SsidFieldNumber = 1;
    private pb::ByteString ssid_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Ssid {
      get { return ssid_; }
      set {
        ssid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "channel" field.</summary>
    public const int ChannelFieldNumber = 2;
    private uint channel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Channel {
      get { return channel_; }
      set {
        channel_ = value;
      }
    }

    /// <summary>Field number for the "rssi" field.</summary>
    public const int RssiFieldNumber = 3;
    private int rssi_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Rssi {
      get { return rssi_; }
      set {
        rssi_ = value;
      }
    }

    /// <summary>Field number for the "bssid" field.</summary>
    public const int BssidFieldNumber = 4;
    private pb::ByteString bssid_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Bssid {
      get { return bssid_; }
      set {
        bssid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "auth" field.</summary>
    public const int AuthFieldNumber = 5;
    private global::Espressif.WifiAuthMode auth_ = global::Espressif.WifiAuthMode.Open;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Espressif.WifiAuthMode Auth {
      get { return auth_; }
      set {
        auth_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WiFiScanResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WiFiScanResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Ssid != other.Ssid) return false;
      if (Channel != other.Channel) return false;
      if (Rssi != other.Rssi) return false;
      if (Bssid != other.Bssid) return false;
      if (Auth != other.Auth) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Ssid.Length != 0) hash ^= Ssid.GetHashCode();
      if (Channel != 0) hash ^= Channel.GetHashCode();
      if (Rssi != 0) hash ^= Rssi.GetHashCode();
      if (Bssid.Length != 0) hash ^= Bssid.GetHashCode();
      if (Auth != global::Espressif.WifiAuthMode.Open) hash ^= Auth.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Ssid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Ssid);
      }
      if (Channel != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Channel);
      }
      if (Rssi != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Rssi);
      }
      if (Bssid.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Bssid);
      }
      if (Auth != global::Espressif.WifiAuthMode.Open) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Auth);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Ssid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Ssid);
      }
      if (Channel != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Channel);
      }
      if (Rssi != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Rssi);
      }
      if (Bssid.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Bssid);
      }
      if (Auth != global::Espressif.WifiAuthMode.Open) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Auth);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Ssid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Ssid);
      }
      if (Channel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Channel);
      }
      if (Rssi != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rssi);
      }
      if (Bssid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Bssid);
      }
      if (Auth != global::Espressif.WifiAuthMode.Open) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Auth);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WiFiScanResult other) {
      if (other == null) {
        return;
      }
      if (other.Ssid.Length != 0) {
        Ssid = other.Ssid;
      }
      if (other.Channel != 0) {
        Channel = other.Channel;
      }
      if (other.Rssi != 0) {
        Rssi = other.Rssi;
      }
      if (other.Bssid.Length != 0) {
        Bssid = other.Bssid;
      }
      if (other.Auth != global::Espressif.WifiAuthMode.Open) {
        Auth = other.Auth;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Ssid = input.ReadBytes();
            break;
          }
          case 16: {
            Channel = input.ReadUInt32();
            break;
          }
          case 24: {
            Rssi = input.ReadInt32();
            break;
          }
          case 34: {
            Bssid = input.ReadBytes();
            break;
          }
          case 40: {
            Auth = (global::Espressif.WifiAuthMode) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Ssid = input.ReadBytes();
            break;
          }
          case 16: {
            Channel = input.ReadUInt32();
            break;
          }
          case 24: {
            Rssi = input.ReadInt32();
            break;
          }
          case 34: {
            Bssid = input.ReadBytes();
            break;
          }
          case 40: {
            Auth = (global::Espressif.WifiAuthMode) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RespScanResult : pb::IMessage<RespScanResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RespScanResult> _parser = new pb::MessageParser<RespScanResult>(() => new RespScanResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RespScanResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Espressif.WifiScanReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespScanResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespScanResult(RespScanResult other) : this() {
      entries_ = other.entries_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespScanResult Clone() {
      return new RespScanResult(this);
    }

    /// <summary>Field number for the "entries" field.</summary>
    public const int EntriesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Espressif.WiFiScanResult> _repeated_entries_codec
        = pb::FieldCodec.ForMessage(10, global::Espressif.WiFiScanResult.Parser);
    private readonly pbc::RepeatedField<global::Espressif.WiFiScanResult> entries_ = new pbc::RepeatedField<global::Espressif.WiFiScanResult>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Espressif.WiFiScanResult> Entries {
      get { return entries_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RespScanResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RespScanResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!entries_.Equals(other.entries_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= entries_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      entries_.WriteTo(output, _repeated_entries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      entries_.WriteTo(ref output, _repeated_entries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += entries_.CalculateSize(_repeated_entries_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RespScanResult other) {
      if (other == null) {
        return;
      }
      entries_.Add(other.entries_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            entries_.AddEntriesFrom(input, _repeated_entries_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            entries_.AddEntriesFrom(ref input, _repeated_entries_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class WiFiScanPayload : pb::IMessage<WiFiScanPayload>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WiFiScanPayload> _parser = new pb::MessageParser<WiFiScanPayload>(() => new WiFiScanPayload());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WiFiScanPayload> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Espressif.WifiScanReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WiFiScanPayload() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WiFiScanPayload(WiFiScanPayload other) : this() {
      msg_ = other.msg_;
      status_ = other.status_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.CmdScanStart:
          CmdScanStart = other.CmdScanStart.Clone();
          break;
        case PayloadOneofCase.RespScanStart:
          RespScanStart = other.RespScanStart.Clone();
          break;
        case PayloadOneofCase.CmdScanStatus:
          CmdScanStatus = other.CmdScanStatus.Clone();
          break;
        case PayloadOneofCase.RespScanStatus:
          RespScanStatus = other.RespScanStatus.Clone();
          break;
        case PayloadOneofCase.CmdScanResult:
          CmdScanResult = other.CmdScanResult.Clone();
          break;
        case PayloadOneofCase.RespScanResult:
          RespScanResult = other.RespScanResult.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WiFiScanPayload Clone() {
      return new WiFiScanPayload(this);
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 1;
    private global::Espressif.WiFiScanMsgType msg_ = global::Espressif.WiFiScanMsgType.TypeCmdScanStart;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Espressif.WiFiScanMsgType Msg {
      get { return msg_; }
      set {
        msg_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 2;
    private global::Espressif.Status status_ = global::Espressif.Status.Success;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Espressif.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "cmd_scan_start" field.</summary>
    public const int CmdScanStartFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Espressif.CmdScanStart CmdScanStart {
      get { return payloadCase_ == PayloadOneofCase.CmdScanStart ? (global::Espressif.CmdScanStart) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.CmdScanStart;
      }
    }

    /// <summary>Field number for the "resp_scan_start" field.</summary>
    public const int RespScanStartFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Espressif.RespScanStart RespScanStart {
      get { return payloadCase_ == PayloadOneofCase.RespScanStart ? (global::Espressif.RespScanStart) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.RespScanStart;
      }
    }

    /// <summary>Field number for the "cmd_scan_status" field.</summary>
    public const int CmdScanStatusFieldNumber = 12;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Espressif.CmdScanStatus CmdScanStatus {
      get { return payloadCase_ == PayloadOneofCase.CmdScanStatus ? (global::Espressif.CmdScanStatus) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.CmdScanStatus;
      }
    }

    /// <summary>Field number for the "resp_scan_status" field.</summary>
    public const int RespScanStatusFieldNumber = 13;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Espressif.RespScanStatus RespScanStatus {
      get { return payloadCase_ == PayloadOneofCase.RespScanStatus ? (global::Espressif.RespScanStatus) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.RespScanStatus;
      }
    }

    /// <summary>Field number for the "cmd_scan_result" field.</summary>
    public const int CmdScanResultFieldNumber = 14;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Espressif.CmdScanResult CmdScanResult {
      get { return payloadCase_ == PayloadOneofCase.CmdScanResult ? (global::Espressif.CmdScanResult) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.CmdScanResult;
      }
    }

    /// <summary>Field number for the "resp_scan_result" field.</summary>
    public const int RespScanResultFieldNumber = 15;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Espressif.RespScanResult RespScanResult {
      get { return payloadCase_ == PayloadOneofCase.RespScanResult ? (global::Espressif.RespScanResult) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.RespScanResult;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      CmdScanStart = 10,
      RespScanStart = 11,
      CmdScanStatus = 12,
      RespScanStatus = 13,
      CmdScanResult = 14,
      RespScanResult = 15,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WiFiScanPayload);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WiFiScanPayload other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Msg != other.Msg) return false;
      if (Status != other.Status) return false;
      if (!object.Equals(CmdScanStart, other.CmdScanStart)) return false;
      if (!object.Equals(RespScanStart, other.RespScanStart)) return false;
      if (!object.Equals(CmdScanStatus, other.CmdScanStatus)) return false;
      if (!object.Equals(RespScanStatus, other.RespScanStatus)) return false;
      if (!object.Equals(CmdScanResult, other.CmdScanResult)) return false;
      if (!object.Equals(RespScanResult, other.RespScanResult)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Msg != global::Espressif.WiFiScanMsgType.TypeCmdScanStart) hash ^= Msg.GetHashCode();
      if (Status != global::Espressif.Status.Success) hash ^= Status.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.CmdScanStart) hash ^= CmdScanStart.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.RespScanStart) hash ^= RespScanStart.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.CmdScanStatus) hash ^= CmdScanStatus.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.RespScanStatus) hash ^= RespScanStatus.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.CmdScanResult) hash ^= CmdScanResult.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.RespScanResult) hash ^= RespScanResult.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Msg != global::Espressif.WiFiScanMsgType.TypeCmdScanStart) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Msg);
      }
      if (Status != global::Espressif.Status.Success) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
      if (payloadCase_ == PayloadOneofCase.CmdScanStart) {
        output.WriteRawTag(82);
        output.WriteMessage(CmdScanStart);
      }
      if (payloadCase_ == PayloadOneofCase.RespScanStart) {
        output.WriteRawTag(90);
        output.WriteMessage(RespScanStart);
      }
      if (payloadCase_ == PayloadOneofCase.CmdScanStatus) {
        output.WriteRawTag(98);
        output.WriteMessage(CmdScanStatus);
      }
      if (payloadCase_ == PayloadOneofCase.RespScanStatus) {
        output.WriteRawTag(106);
        output.WriteMessage(RespScanStatus);
      }
      if (payloadCase_ == PayloadOneofCase.CmdScanResult) {
        output.WriteRawTag(114);
        output.WriteMessage(CmdScanResult);
      }
      if (payloadCase_ == PayloadOneofCase.RespScanResult) {
        output.WriteRawTag(122);
        output.WriteMessage(RespScanResult);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Msg != global::Espressif.WiFiScanMsgType.TypeCmdScanStart) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Msg);
      }
      if (Status != global::Espressif.Status.Success) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
      if (payloadCase_ == PayloadOneofCase.CmdScanStart) {
        output.WriteRawTag(82);
        output.WriteMessage(CmdScanStart);
      }
      if (payloadCase_ == PayloadOneofCase.RespScanStart) {
        output.WriteRawTag(90);
        output.WriteMessage(RespScanStart);
      }
      if (payloadCase_ == PayloadOneofCase.CmdScanStatus) {
        output.WriteRawTag(98);
        output.WriteMessage(CmdScanStatus);
      }
      if (payloadCase_ == PayloadOneofCase.RespScanStatus) {
        output.WriteRawTag(106);
        output.WriteMessage(RespScanStatus);
      }
      if (payloadCase_ == PayloadOneofCase.CmdScanResult) {
        output.WriteRawTag(114);
        output.WriteMessage(CmdScanResult);
      }
      if (payloadCase_ == PayloadOneofCase.RespScanResult) {
        output.WriteRawTag(122);
        output.WriteMessage(RespScanResult);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Msg != global::Espressif.WiFiScanMsgType.TypeCmdScanStart) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Msg);
      }
      if (Status != global::Espressif.Status.Success) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (payloadCase_ == PayloadOneofCase.CmdScanStart) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CmdScanStart);
      }
      if (payloadCase_ == PayloadOneofCase.RespScanStart) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RespScanStart);
      }
      if (payloadCase_ == PayloadOneofCase.CmdScanStatus) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CmdScanStatus);
      }
      if (payloadCase_ == PayloadOneofCase.RespScanStatus) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RespScanStatus);
      }
      if (payloadCase_ == PayloadOneofCase.CmdScanResult) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CmdScanResult);
      }
      if (payloadCase_ == PayloadOneofCase.RespScanResult) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RespScanResult);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WiFiScanPayload other) {
      if (other == null) {
        return;
      }
      if (other.Msg != global::Espressif.WiFiScanMsgType.TypeCmdScanStart) {
        Msg = other.Msg;
      }
      if (other.Status != global::Espressif.Status.Success) {
        Status = other.Status;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.CmdScanStart:
          if (CmdScanStart == null) {
            CmdScanStart = new global::Espressif.CmdScanStart();
          }
          CmdScanStart.MergeFrom(other.CmdScanStart);
          break;
        case PayloadOneofCase.RespScanStart:
          if (RespScanStart == null) {
            RespScanStart = new global::Espressif.RespScanStart();
          }
          RespScanStart.MergeFrom(other.RespScanStart);
          break;
        case PayloadOneofCase.CmdScanStatus:
          if (CmdScanStatus == null) {
            CmdScanStatus = new global::Espressif.CmdScanStatus();
          }
          CmdScanStatus.MergeFrom(other.CmdScanStatus);
          break;
        case PayloadOneofCase.RespScanStatus:
          if (RespScanStatus == null) {
            RespScanStatus = new global::Espressif.RespScanStatus();
          }
          RespScanStatus.MergeFrom(other.RespScanStatus);
          break;
        case PayloadOneofCase.CmdScanResult:
          if (CmdScanResult == null) {
            CmdScanResult = new global::Espressif.CmdScanResult();
          }
          CmdScanResult.MergeFrom(other.CmdScanResult);
          break;
        case PayloadOneofCase.RespScanResult:
          if (RespScanResult == null) {
            RespScanResult = new global::Espressif.RespScanResult();
          }
          RespScanResult.MergeFrom(other.RespScanResult);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Msg = (global::Espressif.WiFiScanMsgType) input.ReadEnum();
            break;
          }
          case 16: {
            Status = (global::Espressif.Status) input.ReadEnum();
            break;
          }
          case 82: {
            global::Espressif.CmdScanStart subBuilder = new global::Espressif.CmdScanStart();
            if (payloadCase_ == PayloadOneofCase.CmdScanStart) {
              subBuilder.MergeFrom(CmdScanStart);
            }
            input.ReadMessage(subBuilder);
            CmdScanStart = subBuilder;
            break;
          }
          case 90: {
            global::Espressif.RespScanStart subBuilder = new global::Espressif.RespScanStart();
            if (payloadCase_ == PayloadOneofCase.RespScanStart) {
              subBuilder.MergeFrom(RespScanStart);
            }
            input.ReadMessage(subBuilder);
            RespScanStart = subBuilder;
            break;
          }
          case 98: {
            global::Espressif.CmdScanStatus subBuilder = new global::Espressif.CmdScanStatus();
            if (payloadCase_ == PayloadOneofCase.CmdScanStatus) {
              subBuilder.MergeFrom(CmdScanStatus);
            }
            input.ReadMessage(subBuilder);
            CmdScanStatus = subBuilder;
            break;
          }
          case 106: {
            global::Espressif.RespScanStatus subBuilder = new global::Espressif.RespScanStatus();
            if (payloadCase_ == PayloadOneofCase.RespScanStatus) {
              subBuilder.MergeFrom(RespScanStatus);
            }
            input.ReadMessage(subBuilder);
            RespScanStatus = subBuilder;
            break;
          }
          case 114: {
            global::Espressif.CmdScanResult subBuilder = new global::Espressif.CmdScanResult();
            if (payloadCase_ == PayloadOneofCase.CmdScanResult) {
              subBuilder.MergeFrom(CmdScanResult);
            }
            input.ReadMessage(subBuilder);
            CmdScanResult = subBuilder;
            break;
          }
          case 122: {
            global::Espressif.RespScanResult subBuilder = new global::Espressif.RespScanResult();
            if (payloadCase_ == PayloadOneofCase.RespScanResult) {
              subBuilder.MergeFrom(RespScanResult);
            }
            input.ReadMessage(subBuilder);
            RespScanResult = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Msg = (global::Espressif.WiFiScanMsgType) input.ReadEnum();
            break;
          }
          case 16: {
            Status = (global::Espressif.Status) input.ReadEnum();
            break;
          }
          case 82: {
            global::Espressif.CmdScanStart subBuilder = new global::Espressif.CmdScanStart();
            if (payloadCase_ == PayloadOneofCase.CmdScanStart) {
              subBuilder.MergeFrom(CmdScanStart);
            }
            input.ReadMessage(subBuilder);
            CmdScanStart = subBuilder;
            break;
          }
          case 90: {
            global::Espressif.RespScanStart subBuilder = new global::Espressif.RespScanStart();
            if (payloadCase_ == PayloadOneofCase.RespScanStart) {
              subBuilder.MergeFrom(RespScanStart);
            }
            input.ReadMessage(subBuilder);
            RespScanStart = subBuilder;
            break;
          }
          case 98: {
            global::Espressif.CmdScanStatus subBuilder = new global::Espressif.CmdScanStatus();
            if (payloadCase_ == PayloadOneofCase.CmdScanStatus) {
              subBuilder.MergeFrom(CmdScanStatus);
            }
            input.ReadMessage(subBuilder);
            CmdScanStatus = subBuilder;
            break;
          }
          case 106: {
            global::Espressif.RespScanStatus subBuilder = new global::Espressif.RespScanStatus();
            if (payloadCase_ == PayloadOneofCase.RespScanStatus) {
              subBuilder.MergeFrom(RespScanStatus);
            }
            input.ReadMessage(subBuilder);
            RespScanStatus = subBuilder;
            break;
          }
          case 114: {
            global::Espressif.CmdScanResult subBuilder = new global::Espressif.CmdScanResult();
            if (payloadCase_ == PayloadOneofCase.CmdScanResult) {
              subBuilder.MergeFrom(CmdScanResult);
            }
            input.ReadMessage(subBuilder);
            CmdScanResult = subBuilder;
            break;
          }
          case 122: {
            global::Espressif.RespScanResult subBuilder = new global::Espressif.RespScanResult();
            if (payloadCase_ == PayloadOneofCase.RespScanResult) {
              subBuilder.MergeFrom(RespScanResult);
            }
            input.ReadMessage(subBuilder);
            RespScanResult = subBuilder;
            break;
          }
        }
      }
    }

        internal byte[] toByteArray()
        {
            throw new NotImplementedException();
        }
#endif

    }

  #endregion

}

#endregion Designer generated code
